name: Create Environment File
description: Creates an env file with all secrets and env variables.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Create env file
      shell: bash
      run: |
        touch env.properties
        echo REVENUECAT_API_KEY=${{ secrets.REVENUECAT_API_KEY }} >> env.properties
        cat env.properties