name: Build and upload windows executable

on:
  workflow_call:


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: ./gradlew.bat

      - name: Build EXE
        run: ./gradlew.bat packageExe

      - name: Check if exists
        run: |
          if [ -f ./desktopApp/compose/binaries/main/exe/*.exe ]; then
          echo "EXE exists."
          else
          echo "EXE does not exist." >&2
          exit 1
          fi
        continue-on-error: false

      - name: GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.tagname }}"
          prerelease: false
          files: |
            ./desktopApp/compose/binaries/main/exe/*.exe