name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Version name'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.tagname }}',
              sha: context.sha
            })

  build-android:
    needs: create-tag
    uses: /.github/workflows/build-android.yml
    secrets: inherit

  build-windows:
    needs: create-tag
    uses: /.github/workflows/build-windows.yml
    secrets: inherit