name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Version name'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.tagname }}',
              sha: context.sha
            })

      - uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >
            ${{ runner.os }}-gradle-
            ${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Update dependencies
        run: ./gradlew dependencies

      - name: Decode Release Key
        run: |
          echo "${{ secrets.KEYSTORE_DECRYPT_SECRET }}" > ./androidApp/${{ vars.KEYSTORE_FILE_NAME }}.asc &&
          echo "Decrypting file: ./androidApp/${{ vars.KEYSTORE_FILE_NAME }}.asc" &&
          echo "Output file will be: ./androidApp/${{ vars.KEYSTORE_FILE_NAME }}" &&
          gpg --batch --yes --decrypt --passphrase "${{ secrets.KEYSTORE_DECRYPT_PASSWORD }}" ./androidApp/${{ vars.KEYSTORE_FILE_NAME }}.asc > ./androidApp/${{ vars.KEYSTORE_FILE_NAME }} &&
          rm ./androidApp/${{ vars.KEYSTORE_FILE_NAME }}.asc
        continue-on-error: false

      - name: Check Release Key is created
        run: |
          if [ -f ./androidApp/${{ vars.KEYSTORE_FILE_NAME }} ]; then
          echo "Release key exists."
          else
          echo "Release key does not exist." >&2
          exit 1
          fi
        continue-on-error: false

      - name: Build Signed Bundle (AAB)
        run: ./gradlew bundleRelease --stacktrace

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_OUTPUT

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: ${{ steps.releaseAab.outputs.aabfile }} ${{ steps.releaseApk.outputs.apkfile }}
          dest: ${{ steps.releaseApk.outputs.apkfile }}.zip

      - name: Upload ZIP to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: ${{ steps.releaseApk.outputs.apkfile }}.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          release_name: ${{ github.event.inputs.tagname }}
          draft: false
          prerelease: false

      - name: Upload files to GitHub Release
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ${{ steps.releaseApk.outputs.apkfile }}.zip