name: Deploy Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build-signed-bundle:
    uses: ./.github/workflows/build_signed_bundle.yml
    secrets: inherit

  create-github-release:
    uses: ./.github/workflows/github_release.yml
    needs: build-signed-bundle
    secrets: inherit