name: Deploy Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build-signed-bundle:
    uses: ./.github/workflows/build-signed-bundle.yml
    needs: create-release-notes
    secrets: inherit